version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: profit-pouch-web
    ports:
      - "3001:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    # Add volumes if you need to persist any data
    # volumes:
    #   - ./your-data:/app/data

    # Add healthcheck to ensure the container is running properly
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  default:
    name: profit-pouch-network
    driver: bridge 